spring.application.name=firstSpringAIProject
server.port=8081

#apikeyForOpenAI
#spring.ai.openai.api-key= ${OPENAI_API_KEY}

#Ollama
spring.ai.ollama.base-url = http://localhost:11434
spring.ai.ollama.chat.options.model = codellama:latest
spring.ai.ollama.chat.options.temperature = 0.7


#spring.ai.ollama.api-key= ${OLLAMA_API_KEY}

